## Flox Environment Manifest -----------------------------------------
##
##   _Everything_ you need to know about the _manifest_ is here:
##
##               https://flox.dev/docs/concepts/manifest
##
## -------------------------------------------------------------------
# Flox manifest version managed by Flox CLI
version = 1


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
docker.pkg-path = "docker"
go.pkg-path = "go"
kind.pkg-path = "kind"
kubectl.pkg-path = "kubectl"
k9s.pkg-path = "k9s"
python311.pkg-path = "python311"
requests.pkg-path = "python311Packages.requests"
# gum.pkg-path = "gum"
# gum.version = "^0.14.5"


## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
AIRBYTE_EMAIL = "localmail@example.com"
AIRBYTE_PASSWORD = "localpassword"
GCLOUD_SERVICE_MAIL = "airbyte-gcloud-sources@airbyte-sources.iam.gserviceaccount.com"
# INTRO_MESSAGE = "It's gettin' Flox in here"

## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
# on-activate = '''
#   # -> Set variables, create files and directories
#   # -> Perform initialization steps, e.g. create a python venv
#   # -> Useful environment variables:
#   #      - FLOX_ENV_PROJECT=/home/user/example
#   #      - FLOX_ENV=/home/user/example/.flox/run
#   #      - FLOX_ENV_CACHE=/home/user/example/.flox/cache
# '''
on-activate = """
  export PATH=$(go env GOPATH)/bin:$PATH

  if ! command -v abctl 2>&1 >/dev/null
  then
      go install github.com/airbytehq/abctl@latest
  fi

  abctl local install
  abctl local credentials --email $AIRBYTE_EMAIL --password $AIRBYTE_PASSWORD

  output=$(abctl local credentials 2>&1 | sed $'s/\u001b\\[[0-9;]*m//g')
  client_id=$(echo "$output" | awk '/Client-Id:/ {print $2}')
  client_secret=$(echo "$output" | awk '/Client-Secret:/ {print $2}')
  export AIRBYTE_CLIENT_ID="$client_id"
  export AIRBYTE_CLIENT_SECRET="$client_secret"
  python airbyte-conf.py
"""


## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
# common = '''
#   gum style \
#   --foreground 212 --border-foreground 212 --border double \
#   --align center --width 50 --margin "1 2" --padding "2 4" \
#     $INTRO_MESSAGE
# '''
## Shell specific profiles go here:
# bash = ...
# zsh  = ...
# fish = ...


## Services ----------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## -------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
# Uncomment to disable CUDA detection.
# cuda-detection = false
